In [21]:
import numpy as np

In [22]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [73]:
a_list+b_list
n_array+n_array

array([2, 4, 6, 8, 10, list([1, 2, 3, 1, 2, 3]), 'temattemat', 200],
      dtype=object)

In [74]:
a_list[3]

4

In [75]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100, 100]


In [76]:
k_krotka[4]

5

In [77]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [28]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [29]:
n_array = np.array(a_list) # wektor numpy

In [30]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat', 100], dtype=object)

In [31]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [32]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [33]:
studenci_slownik["Zosia"]

22

In [34]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [35]:
for elementy in studenci_slownik.items():
    print(elementy)

(123, 123)
('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])
((1, 2), 'Krotka')


In [36]:
for elementy in studenci_slownik.values():
    print(elementy)

123
3
5
22
[2, 21]
Krotka


In [37]:
studenci_slownik["Cuthulu"]= -1000000

In [38]:
studenci_slownik

{123: 123,
 'Igor': 3,
 'Frankek': 5,
 'Zosia': 22,
 'Julia': [2, 21],
 (1, 2): 'Krotka',
 'Cuthulu': -1000000}

In [39]:
stara_lista = ["Igor", "Zosia", "Franek", "nieimie"]
nowa_lista = [imie for imie in stara_lista if imie[0].isupper()] #jeżeli imie zaczyna się wielką literą, wstaw je do listy
print(nowa_lista)

['Igor', 'Zosia', 'Franek']


In [40]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [42]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 123, 1: 'Igor', 2: 'Frankek', 3: 'Zosia', 4: 'Julia', 5: (1, 2), 6: 'Cuthulu'}


In [43]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [44]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [45]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [46]:
1 in a
"Igor" in studenci_slownik

True

## Własne typy

In [47]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [48]:
class Pusta():
    pass

pustostan = Pusta()
type(pustostan)

__main__.Pusta

In [50]:
class Pelna():
    nazwa = "stała"
    
pustostan = Pelna()
type(pustostan)
print(pustostan.nazwa)

stała


In [79]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [80]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [81]:
pio_zajecia.ile_zajec

4

In [57]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [55]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [58]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [59]:
pio_zajecia.ile_mispow()

4

In [60]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [61]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [62]:
print(pio_zajecia.ile_zajec)

5


In [66]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [67]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [68]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [69]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [70]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [82]:
# ma na takie rzeczy być w stanie odpowiedzieć

#numer_lodz = NumerTelefonu("426877868")
#>>> "prawidlowy numer"

#numer_lodz.wojewodztwo 
#>>> "Lodz"

#print(numer_lodz)
#>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

class NumerTelefonu():
    
    poprawnosc = 1
    
    def __init__(self, numer):
        if numer[0:2] == "48" and len(numer) == 11:
            self.numer = numer
            print("Numer {} jest poprawny".format(numer))
        else:
            print("Error! Numer niepoprawny")
            self.poprawnosc = 0
            
    def wojewodztwo(self):
        if self.poprawnosc == 1:
            wojewodztwa = {"Krakow":12,"Krosno":13,"Tarnow":14,"Tarnobrzeg":15,"Przemysl":16,"Rzeszow":17,
                       "Nowy Sacz":18,"Warszawa":22,"Ciechan":23,"Plock":24,"Siedlce":25,"Ostroleka":29,
                       "Katowice":32,"Bielsko-Biala":33,"Czestochowa":34,"Kielce":41,"Lodz":42,"Sieradz":43,
                       "Piotrków Trybunalski":44,"Skierniewice":46,"Radom":48,"Bydgoszcz":52,"Wloclawek":54,
                       "Elblag":55,"Torun":56,"Gdansk":58,"Slupsk":59,"Poznan":61,"Kalisz":62,"Konin":63,"Leszno":65,
                       "Pila":67,"Zielona Gora":68,"Wroclaw":71,"Walbrzych":74,"Jelenia Gora":75,"Legnica":76,
                       "Opole":77,"Lublin":81,"Chelm":82,"Zamosc":84,"Bialystok":85,"Lomza":86,"Suwalki":87,
                       "Olsztyn":89,"Szczecin":91,"Koszalin":94,"Gorzow Wielkopolski":95}
            wiadomosc = "Numer komórkowy"
            for miasto, kierunkowy in wojewodztwa.items():
                if str(kierunkowy) == self.numer[2:4]:
                    wiadomosc = "Numer z miasta: {}".format(miasto)
                    break
            print(wiadomosc)
        else:
            print("Nieznane wojewodztwo. Numer niepoprawny")
            
    def czytaj_cyfry(self):
        cyfry = ["zero","jeden","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć"]
        przeczytane = "Numer to: "
        for cyfra in self.numer:
            przeczytane = przeczytane + str(cyfry[int(cyfra)]) + " "
        print(przeczytane)
        
    pass


In [84]:
numer1 = NumerTelefonu("48429293423")
numer1.wojewodztwo()
numer1.czytaj_cyfry()

Numer 48429293423 jest poprawny
Numer z miasta: Lodz
Numer to: cztery osiem cztery dwa dziewięć dwa dziewięć trzy cztery dwa trzy 
